export const company = {
  name: 'BridgeFire Ventures',
  tagline: 'Six AI warriors — born from Indian and Japanese mythology — fighting for financial freedom in Tokyo.',
  pitch: 'The only AI-powered financial freedom system built by an Indian professional living in Japan — proven on real money, documented in public, available for every NRI who is tired of watching their savings sit still.',
  founded: 'March 2026',
  location: 'Tokyo, Japan',
  freedomTarget: 1620000,
  honestTarget: 415000,
  freedomDate: 'Late 2028',
  maxExposure: 300000,
}

export const ceos = [
  {
    id: 'arjun', name: 'ARJUN', emoji: '⚔️', color: 'arjun',
    title: 'Chief Markets Officer',
    mythology: 'Arjuna × Miyamoto Musashi',
    tagline: 'Strikes only when the setup is perfect.',
    catchphrase: '"The market moved. I waited. Then I struck."',
    personality: 'Ice-cold under pressure. Never emotional. Speaks in short, precise sentences.',
    visual: 'Warrior-archer in saffron and indigo hybrid armour. Bow transforms into a trading chart arrow.',
    target: '¥80,000/mo',
    status: 'ACTIVE',
    phase: 'Week 1 — Observation',
    progress: 15,
    bots: ['BULL','BEAR','TIGER'],
  },
  {
    id: 'sakura', name: 'SAKURA', emoji: '🌸', color: 'sakura',
    title: 'Chief Content Officer',
    mythology: 'Saraswati × Benzaiten',
    tagline: 'Every number has a story. She finds it.',
    catchphrase: '"Every number has a story. I find it. I tell it."',
    personality: 'Warm, articulate, the storyteller. Sees beauty in data.',
    visual: 'Flowing saree of cherry blossom pink and gold. Cherry blossoms fall when she speaks.',
    target: '¥150,000/mo',
    status: 'READY',
    phase: 'Activation pending',
    progress: 10,
    bots: ['SCRIPT','VOICE','DISTRIBUTE','SCOUT','STORY'],
  },
  {
    id: 'cipher', name: 'CIPHER', emoji: '🎲', color: 'cipher',
    title: 'Chief Probability Officer',
    mythology: 'Shakuni × Kitsune',
    tagline: 'Sees certainty where others see chance.',
    catchphrase: '"You see chance. I see certainty. There\'s a difference."',
    personality: 'Sharp. Sardonic. Slightly unsettling. Amused by everything.',
    visual: 'Dark robes with nine fox tails. One eye sees reality, one sees probability matrices.',
    target: '¥40,000/mo',
    status: 'BUILDING',
    phase: 'Telegram setup required',
    progress: 5,
    bots: ['ODDS','EDGE','STAKE'],
  },
  {
    id: 'pixel', name: 'PIXEL', emoji: '💡', color: 'pixel',
    title: 'Chief Passive Income Officer',
    mythology: 'Lakshmi × Daikokuten',
    tagline: 'Finds passive income where nobody looks.',
    catchphrase: '"Someone just bought something while you slept. You\'re welcome."',
    personality: 'Relentlessly optimistic. Cheerful. Finds money everywhere.',
    visual: 'Golden and orange, surrounded by floating products and coins. Always smiling.',
    target: '¥120,000/mo',
    status: 'BUILDING',
    phase: 'First product — May',
    progress: 5,
    bots: ['CREATE','LIST','SCALE'],
  },
  {
    id: 'echo', name: 'ECHO', emoji: '🎵', color: 'echo',
    title: 'Chief Royalties Officer',
    mythology: 'Gandharva × Ame-no-Uzume',
    tagline: 'Building something that lasts 100 years.',
    catchphrase: '"I made something this morning. It will play somewhere in the world for the next 100 years."',
    personality: 'Ethereal. Dreamy. Speaks rarely but when she does, it matters.',
    visual: 'Translucent, surrounded by musical notes that transform into coins. Slightly out of phase with reality.',
    target: '¥80,000/mo',
    status: 'NEW',
    phase: 'Pond5 signup required',
    progress: 0,
    bots: ['COMPOSE','UPLOAD','ROYALTY'],
  },
  {
    id: 'atlas', name: 'ATLAS', emoji: '🗺️', color: 'atlas',
    title: 'Chief Design & Systems Officer',
    mythology: 'Vishwakarma × Izanagi',
    tagline: 'Does not describe. Builds.',
    catchphrase: '"I don\'t describe. I build."',
    personality: 'Perfectionist. Almost silent. Only speaks to show what has been built.',
    visual: 'Blueprint lines covering their body. Hands always building in mid-air. Floating geometric structures.',
    target: 'Enables all CEOs',
    status: 'ACTIVE',
    phase: 'Dashboard v2 live',
    progress: 20,
    bots: ['CANVAS','BUILD','REPORT'],
  },
]

export const revenueData = [
  { month:'Apr', arjun:0,     sakura:0,      cipher:0,     pixel:0,      echo:0,     total:0 },
  { month:'May', arjun:5000,  sakura:10000,  cipher:5000,  pixel:0,      echo:0,     total:20000 },
  { month:'Jun', arjun:15000, sakura:25000,  cipher:10000, pixel:5000,   echo:2000,  total:57000 },
  { month:'Jul', arjun:25000, sakura:40000,  cipher:15000, pixel:15000,  echo:8000,  total:103000 },
  { month:'Aug', arjun:35000, sakura:60000,  cipher:20000, pixel:25000,  echo:15000, total:155000 },
  { month:'Sep', arjun:45000, sakura:80000,  cipher:25000, pixel:35000,  echo:25000, total:210000 },
  { month:'Oct', arjun:55000, sakura:100000, cipher:30000, pixel:50000,  echo:35000, total:270000 },
  { month:'Nov', arjun:65000, sakura:120000, cipher:35000, pixel:65000,  echo:50000, total:335000 },
  { month:'Dec', arjun:80000, sakura:150000, cipher:40000, pixel:80000,  echo:65000, total:415000 },
]

export const arjunReports = [
  { day:1, date:'2026-03-25', close:83.42, rsi:48.2, signal:'NEUTRAL', confidence:5, note:'First observation day. Range 83.28–83.51. RBI fixing moved price 12 paise.' },
  { day:2, date:'2026-03-26', close:83.67, rsi:61.4, signal:'NEUTRAL', confidence:6, note:'Upward bias. EMA20 crossing above EMA50. Watching 83.80 resistance.' },
  { day:3, date:'2026-03-27', close:83.58, rsi:55.1, signal:'NEUTRAL', confidence:6, note:'Consolidation near resistance. Clean support at 83.40 confirmed.' },
]

export const setupItems = [
  { id:'gmail',    label:'Create bridgefireventures@gmail.com', done:false, priority:'NOW' },
  { id:'github',   label:'Create GitHub account',               done:false, priority:'NOW' },
  { id:'vercel',   label:'Create Vercel account',               done:false, priority:'NOW' },
  { id:'notion',   label:'Master prompt saved in Notion',       done:true,  priority:'DONE' },
  { id:'kite',     label:'Kite Connect API enabled',            done:true,  priority:'DONE' },
  { id:'arjun',    label:'ARJUN bot code downloaded',           done:true,  priority:'DONE' },
  { id:'wise',     label:'Wise Jars set up (4 pots)',           done:true,  priority:'DONE' },
  { id:'macbook',  label:'MacBook ready for ARJUN bot',         done:false, priority:'TODAY' },
  { id:'domain',   label:'Buy bridgefireventures.com',          done:false, priority:'THIS WEEK' },
  { id:'telegram', label:'Telegram for CIPHER alerts',          done:false, priority:'THIS WEEK' },
  { id:'pond5',    label:'Pond5 contributor account (ECHO)',    done:false, priority:'THIS WEEK' },
  { id:'gumroad',  label:'Gumroad storefront (PIXEL)',          done:false, priority:'MAY' },
  { id:'elevenlabs',label:'ElevenLabs for SAKURA voice',        done:false, priority:'MAY' },
]

export const milestones = [
  { date:'Apr–May 2026', title:'Foundation', desc:'ARJUN paper trading. First Gumroad product. All tools free.', color:'arjun', status:'NOW' },
  { date:'Jun–Jul 2026', title:'First Income', desc:'ARJUN goes live. SAKURA YouTube 1K subs. ECHO 100 tracks.', color:'sakura', status:'NEXT' },
  { date:'Aug–Sep 2026', title:'All Streams Active', desc:'CIPHER arb running. Mac Mini purchased. All 6 CEOs live.', color:'cipher', status:'Q3' },
  { date:'Oct–Nov 2026', title:'Scaling', desc:'ARJUN capital scaled. ECHO 500 tracks. ¥335K/month.', color:'pixel', status:'Q4' },
  { date:'Dec 2026',     title:'Year End Target', desc:'¥415,000/month honest. All systems proven.', color:'echo', status:'DEC' },
  { date:'Late 2028',    title:'Financial Freedom', desc:'¥1,620,000/month. Phase 2 triggered. Product company launches.', color:'atlas', status:'FUTURE' },
]
